# Generated by Django 2.2.1 on 2019-05-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitstop_app', '0002_auto_20190504_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(max_length=30)),
                ('temperature', models.IntegerField()),
                ('car_model', models.CharField(max_length=50)),
                ('driver_id', models.IntegerField()),
            ],
        ),
    ]
